version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - default-network
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
#      - ./db-data/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  default-network:
    driver: bridge
